# NAMING
  RunName: HPV16_panel_Sara_Opsaet_11A_830
  startPreviousRun: false
  
# QUALITY FILTERING
  qualityFilt: true
  QualTrim: 20
  MinLen: 50
  MaxLen: 320

# GENO AND SUBTYPING
  CovMatrixGenoTyping: false
  VirStrainGenoTyping: true
  VirStrainSubTyping: true
  VirSGenoTypingTop: 2
  VirSSubTypingTop: 3
  VirStrainMaindb: Combined_mainlines_wRevised_wHPV-mTypes
  VirStrainSubFolders: VirStrainDBs_HPV_sub
 
# REFERENCES
  indexReferences: false 
  sameRefForAll: false
  sRef: HPV16_K02718_1_revised
 
# MODULES 
  DebugMode: true
  CombineRefs: true
  AlignAndVariantCall: true
  AnnotateVariants: true
  Summarize: true
