# NAMING
  RunName: Test_forsog1
  
# QUALITY FILTERING
  qualityFilt: true
  QualTrim: 20
  MinLen: 50
  MaxLen: 320

# GENO AND SUBTYPING
  CovMatrixGenoTyping: true
  HouseGeneEndRow: 5
  VirStrainGenoTyping: false
  VirSGenoTypingTop: 2
  VirSSubTypingTop: 3
  VirStrainMaindb: Combined_mainlines_wRevised_wHPV-mTypes
  VirStrainSubFolders: VirStrainDBs_HPV_sub
 
# REFERENCES
  indexReferences: false 
  sameRefForAll: false
  sRef: HPV16_K02718_1_revised
 
# MODULES 
  AlignAndVariantCall: true
  AnnotateVariants: true
  DebugMode: true
  startPreviousRun: false
