# NAMING
  RunName: Test_forsog1
  
# QUALITY FILTERING
  qualityFilt: true
  QualTrim: 20
  MinLen: 50
  MaxLen: 320

# COVERAGE MATRIX GENOTYPING
  CovMatrixGenoTyping: true
  MinReadsToCountAmpliconAsCovered: 1
  MinNumberOfAmpliconsToConsiderType: 2
  RatioToConfirmType: 1
  HouseGeneEndRow: 5
  
# INTEGRATION DETECTION
  MinDepthOnSampleToCheck: 50
  LimitForIntCall: 50 
  MinRatioForIntCall: 5

# VIRSTRAIN GENOTYPING
  VirStrainGenoTyping: false
  VirSGenoTypingTop: 2

# VIRSTRAIN SUBTYPING
  VirStrainMaindb: Combined_mainlines_wRevised_wHPV-mTypes
  VirSSubTypingTop: 3
  VirStrainSubFolders: VirStrainDBs_HPV_sub
 
# REFERENCES
  indexReferences: false 
  sameRefForAll: false
  sRef: HPV16_K02718_1_revised
 
# MODULES 
  AlignAndVariantCall: true
  AnnotateVariants: true
  DebugMode: true
  startPreviousRun: false
