# NAMING
  RunName: Reanalyze_user_S5-0184-347-HPV_genotypering_Sara_Opsaet_10_A
  
# QUALITY FILTERING
  qualityFilt: true
  QualTrim: 20
  MinLen: 50
  MaxLen: 320

# GENO AND SUBTYPING
  CovMatrixGenoTyping: true
  HouseGeneEndRow: 5
  VirStrainGenoTyping: false
  VirStrainSubTyping: true
  VirSGenoTypingTop: 2
  VirSSubTypingTop: 2
  VirStrainMaindb: Combined_mainlines_wRevised_wHPV-mTypes
  VirStrainSubFolders: VirStrainDBs_HPV_sub
 
# REFERENCES
  indexReferences: false 
  sameRefForAll: false
  sRef: HPV16_K02718_1_revised
 
# MODULES 
  CombineRefs: true
  AlignAndVariantCall: true
  AnnotateVariants: true
  DebugMode: true
  startPreviousRun: false
